In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('../[Data]-Quora-Question-Pairs/train_feats.csv')

In [3]:
train.head()

question1  \
0          step step guide invest share market india   
1                    story kohinoor koh noor diamond   
2       increase speed internet connection using vpn   
3                              mentally lonely solve   
4  dissolve water quikly sugar salt methane carbo...   

                                           question2  is_duplicate    Jaccard  \
0                step step guide invest share market             0  83.333333   
1  happen indian government stole kohinoor koh no...             0  44.444444   
2               internet speed increased hacking dns             0  22.222222   
3                        remainder math math divided             0   0.000000   
4                            fish survive salt water             0  20.000000   

   Fuzz Ratio  Fuzz WRatio  Fuzz QRatio  Fuzz Partial Ratio  \
0          92           95           92                 100   
1          67           86           67                  94   
2          55           62           55                  46   
3          25           27           25                  29   
4          29           86           29                  57   

   Fuzz Token Sort Ratio  Fuzz Token Set Ratio  CosineTFIDF  CosineBin  
0                     92                   100     0.946475   0.912871  
1                     67                    89     0.658507   0.602464  
2                     65                    65     0.119545   0.227921  
3                     25                    28     0.000000   0.000000  
4                     47                    61     0.103536   0.210819

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
X_train, X_test, y_train, y_test = train_test_split(train.drop(['question1', 'question2', 'is_duplicate'], axis=1),
                                                    train['is_duplicate'], test_size=0.3)

In [6]:
from sklearn.linear_model import SGDClassifier, LogisticRegression

# SGD Classifier 
with loss=log

In [7]:
model = SGDClassifier(loss='log')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

D:\Users\Ritvik\Anaconda3\envs\datascience\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


[[73607 40140]
 [ 2749  4791]]
              precision    recall  f1-score   support

           0       0.96      0.65      0.77    113747
           1       0.11      0.64      0.18      7540

   micro avg       0.65      0.65      0.65    121287
   macro avg       0.54      0.64      0.48    121287
weighted avg       0.91      0.65      0.74    121287



# SGD Classifier 
with loss=hinge

In [8]:
model = SGDClassifier(loss='hinge')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

D:\Users\Ritvik\Anaconda3\envs\datascience\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


[[44022  8531]
 [32334 36400]]
              precision    recall  f1-score   support

           0       0.58      0.84      0.68     52553
           1       0.81      0.53      0.64     68734

   micro avg       0.66      0.66      0.66    121287
   macro avg       0.69      0.68      0.66    121287
weighted avg       0.71      0.66      0.66    121287



# Logistic Regression

In [9]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

D:\Users\Ritvik\Anaconda3\envs\datascience\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[59264 21216]
 [17092 23715]]
              precision    recall  f1-score   support

           0       0.78      0.74      0.76     80480
           1       0.53      0.58      0.55     40807

   micro avg       0.68      0.68      0.68    121287
   macro avg       0.65      0.66      0.65    121287
weighted avg       0.69      0.68      0.69    121287

